### ISSUE TITLE
Code review of your repo

### ISSUE THREAD

**Issue by ggurbet** [FLATLAY/droplinked_casper#1]
Hi. I am doing the code review of your grant on behalf of CRDAO for DEVxDAO. There are some issues with the repo to pass the requirements. I emailed you two weeks ago but did not receive a reply. However, I see that you updated the repo in the meantime. Please contact me immediately at crdao [ at ] ggurbet [ dot ] com email address if you can fix those issues or I have to fail the review in 24 hours.

**Comment by Alisammour** [comment]
Hi CR Dao,


Looping in my CTO/co-founder Morteza to help with the request. Also the repo was updated and contains all the following code related to the milestones:


https://github.com/FLATLAY/droplinked_casper/blob/main/readme.md

Hi. I am doing the code review of your grant on behalf of CRDAO for DEVxDAO. There are some issues with the repo to pass the requirements. I emailed you two weeks ago but did not receive a reply. However, I see that you updated the repo in the meantime. Please contact me immediately at crdao [ at ] ggurbet [ dot ] com email address if you can fix those issues or I have to fail the review in 24 hours.

**Comment by Alisammour** [comment]
> Hi. I am doing the code review of your grant on behalf of CRDAO for DEVxDAO. There are some issues with the repo to pass the requirements. I emailed you two weeks ago but did not receive a reply. However, I see that you updated the repo in the meantime. Please contact me immediately at crdao [ at ] ggurbet [ dot ] com email address if you can fix those issues or I have to fail the review in 24 hours.

@ggurbet can you share the repo issues here so we can address them? We've updated the README file inside this repo along with supplying the following to the grant review team earlier for Milestones 1-3:

https://gist.github.com/k3rn3lpanicc/af78301897a513a70b61de3cf6ad37ac

https://gist.github.com/k3rn3lpanicc/976f048998865659f531a127e3c4fa43
